# Generated by Django 2.1.8 on 2019-04-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Config key name')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Config value')),
            ],
        ),
    ]
