# Generated by Django 2.1.8 on 2019-04-27 01:41

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Post code, used for url for example')),
                ('title_ja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title in Japanese')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title in English')),
                ('body_ja', markdownx.models.MarkdownxField(blank=True, help_text='Markdown', null=True, verbose_name='Body in Japanese')),
                ('body_en', markdownx.models.MarkdownxField(blank=True, help_text='Markdown', null=True, verbose_name='Body in English')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新時間')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tag', verbose_name='Tag for this post')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Year', verbose_name='Year for this post')),
            ],
        ),
    ]
