# Generated by Django 2.1.8 on 2019-04-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thumbnail image name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tag', verbose_name='Tag for this post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.ForeignKey(blank=True, default=14, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Year', verbose_name='Year for this post'),
        ),
    ]
