# Generated by Django 2.1.8 on 2019-04-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190427_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='Body written with html, this column is used when markdown column is empty'),
        ),
    ]
