# Generated by Django 2.1.8 on 2019-05-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190502_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.ForeignKey(blank=True, default=14, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Year', verbose_name='Year for this post'),
        ),
    ]
