# Generated by Django 2.1.15 on 2020-12-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Year', verbose_name='Year for this post'),
        ),
    ]
