"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = environ.Path(__file__) - 3

env = environ.Env()
env.read_env(os.path.join(BASE_DIR, '.env'))
# env.get_value('DEBUG',cast=bool,default=False)

SLACK_WEBHOOK_URL = env.get_value('SLACK_WEBHOOK_URL', cast=str, default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q7^lwyu$b6fmf!mp)42*j0dosj*(al%6ab_2xpf1qu)-m^*bz$'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',  # Without this, makemigrations doesn't work at least.
    'markdownx',  # Without this, you can't use markdownx on admin at least.
    'axes',  # To use django-axes.
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',   # Must add at the top.
    'django.contrib.auth.backends.ModelBackend',
]

# markdownx が利用する markdown ライブラリの拡張。
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.toc',        # [TOC] で目次。
    'markdown.extensions.extra',      # fenced_code tables がこれに含まれてるらしい。
    'markdown.extensions.attr_list',  # ジッサイあんまり使うことないけど一度は感動したからいれとく。
    # 'markdown.extensions.meta',     # metaはとても便利だったけど、このmarkdownxでは取り出し方がわからない。そしてわかる必要もないのかもしれない。
]
# デフォルトでは、アップロードした画像の最大サイズは500*500。2000*2000くらいにしとく。
MARKDOWNX_IMAGE_MAX_SIZE = {'size': (2000, 2000), 'quality': 100}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # アカウントロック信号を読み取り403にマップする middleware。
]

# Settings for django-axes
# AXES_FAILURE_LIMIT = 5   # How many times does it allow users fail logging in
# AXES_LOCKOUT_TEMPLATE = 'axes_locked.html'   # User template
# AXES_COOLOFF_TIME = 24   # How many hours does it lock ip addresses
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'axes_cache': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
AXES_CACHE = 'axes_cache'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'lookup': 'app.templatetags.template_utils',
            },
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
