# ci は lint と test を行います。
name: ci

# タイミングは pr です。
on:
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:

  ci-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      id: setup-python
      with:
        python-version: 3.6

    - run: |
        python -m pip install --upgrade pip
        python -m pip install flake8

    - uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

    - run: flake8 --config setup.cfg --show-source .
